### PR TITLE
Add elm-oracle autocompletion in place of snippets

### PR DESCRIPTION
**Pull request by brianegan**
Hello there :)

Thanks for the atom package for Elm support! While snippets are handy, it feels like they could be a bit of a pain to keep up to date, might not provide suggestions as intelligently as possible, and are unable to dynamically incorporate modules from your own code.

And as luck would have it, some folks have developed elm-oracle to help out with exactly these problems! I've created this branch to integrate elm-oracle into the language-elm package, and thought I'd see what you think!

If you think it's a good idea, I'd be happy to help maintain it. If not, let me know and I can split it out into a different package :)

Thanks,
Brian

### CODE REVIEW

**Comment by edubkendo** [comment]
I think this is awesome. I was actually hoping to see some things like this happen eventually. I'm using emacs these days and not doing a lot of elm, but if you are happy to maintain this, I'm happy to give you commit bit.

**Comment by edubkendo** [comment]
If you'll ping me when you are happy and merge this, I'll pull down the changes and release a new version.

**Comment by brianegan** [comment]
Cool, thanks so much! Sorry, on vacation, but I found a couple of small issues with this and want to fix em up before I merge it. I'll let you know :)

**Comment by brianegan** [comment]
Hey there! I've gone ahead and made a few improvements to my original code and merged it into master.

Thanks again for being so open to suggestions and improvements :)

Best,
Brian

**Comment by edubkendo** [comment]
Went ahead and published this as a major version since it's such a large change. Very nice work!

**Pull request closed without merging**
